vending_machine_products = [
    {"id":100, "name":"Meed Cookie", "price":2.00},
    {"id":101, "name":"Lays MAX Spicy Mexican Potato Chips", "price":4.00},
    {"id":102, "name":"Lays Cheese-flavored Potato Chips", "price":4.00},
    {"id":103, "name":"Doritos Nacho Cheese", "price":4.00},
    {"id":104, "name":"Doritos Sweet Pepper", "price":4.00},
    {"id":105, "name":"Almarai Chocolate Milk", "price":3.00},
    {"id":106, "name":"Almarai Strawberry Milk", "price":3.00},
    {"id":107, "name":"M & M's", "price":4.00},
    {"id":108, "name":"Al Rabia Orange Juice", "price":3.00},
    {"id":109, "name":"Mars Chocolate Bar", "price":2.00},
    {"id":110, "name":"Galaxy Chocolate Bar", "price":2.00},
    {"id":111, "name":"Canned Ice Tea", "price":3.00},
    {"id":112, "name":"Aquafina Bottle Water", "price":1.00},
    {"id":113, "name":"Packaged TLT Sandwich", "price":1.00},
    {"id":114, "name":"Fruit Cake Slice", "price":3.00},
]
